name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: Test GitHub Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          api-key: ${{ secrets.BONES_API_KEY }}
          project: 'test-project'
          channel: 'release'
          version: '1.0'
          changelog: 'Test release v1.0'
          distro-names: |
            fabric-1.20.1
          distro-groups: |
            fabric
          distro-descriptions: |
            fabric-1.21
          files: |
            dist/*

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
